### ISSUE TITLE
please..

### ISSUE THREAD

**Issue by RelTakeover** [ZfsrGhS953/Petridish-Ogar#8] opened 2016-11-13 11:35 UTC
i have a problem with ogarUL-CLIENT , that client is not compatible with multiogar-edited ( i mean to skins) , you can update to protocol 5 or 6 please , i cant use cigar's client because is soooo laggy

**Comment by ZfsrGhS953** [comment] 2016-11-13 12:35
Duplicate of #7 . I don't own neither MultiOgar-Edited nor OgarUL-Client so I can't update/fix them.

**Closed as completed by ZfsrGhS953** 2016-11-13 12:35 UTC
Labels: duplicate
